import { MinionCard } from '../types/Card';
import { JobType, Trait } from '../types/Enums';
import { CardType, UnitType } from '../types/GameTypes';

// 基础随从卡牌数据
export const minionCards: MinionCard[] = [
    {
        id: 'minion_001',
        name: '小恶魔',
        description: '基础恶魔单位，适合前期使用。',
        type: 'unit',
        cost: 1,
        image: 'imp',
        rarity: 'common',
        imagePath: 'assets/images/minions/imp.png',
        hp: 3,
        atk: 2,
        armor: 0,
        unitType: 'melee',
        jobType: JobType.DEMON,
        traits: [],
        traitValues: {}
    },
    {
        id: 'minion_002',
        name: '蝙蝠恶魔',
        description: '攻击附加中毒效果，每回合造成1点额外伤害，持续2回合。',
        type: 'unit',
        cost: 2,
        image: 'bat',
        rarity: 'common',
        imagePath: 'assets/images/minions/bat_demon.png',
        hp: 2,
        atk: 1,
        armor: 0,
        unitType: 'ranged',
        jobType: JobType.DEMON,
        traits: [Trait.POISON],
        traitValues: { [Trait.POISON]: 1 }
    },
    {
        id: 'minion_003',
        name: '骷髅战士',
        description: '亡灵单位，具有亡语效果：死亡时对相邻敌人造成1点伤害。',
        type: 'unit',
        cost: 2,
        image: 'skeleton',
        rarity: 'common',
        imagePath: 'assets/images/minions/skeleton_warrior.png',
        hp: 2,
        atk: 2,
        armor: 1,
        unitType: 'melee',
        jobType: JobType.UNDEAD,
        traits: [Trait.DEATHRATTLE],
        traitValues: {}
    },
    {
        id: 'minion_004',
        name: '魅魔',
        description: '攻击时回复自身1点生命值。',
        type: 'unit',
        cost: 3,
        image: 'succubus',
        rarity: 'rare',
        imagePath: 'assets/images/minions/succubus.png',
        hp: 4,
        atk: 3,
        armor: 0,
        unitType: 'melee',
        jobType: JobType.DEMON,
        traits: [Trait.HEALING],
        traitValues: { [Trait.HEALING]: 1 }
    },
    {
        id: 'minion_005',
        name: '地狱战犬',
        description: '野兽单位，具有连击特性，每次攻击造成两次伤害。',
        type: 'unit',
        cost: 3,
        image: 'hellhound',
        rarity: 'rare',
        imagePath: 'assets/images/minions/hellhound.png',
        hp: 3,
        atk: 2,
        armor: 0,
        unitType: 'melee',
        jobType: JobType.BEAST,
        traits: [Trait.DOUBLE_ATTACK],
        traitValues: {}
    },
    {
        id: 'minion_006',
        name: '恶魔督军',
        description: '增幅周围友方单位攻击力+1。',
        type: 'unit',
        cost: 4,
        image: 'overseer',
        rarity: 'rare',
        imagePath: 'assets/images/minions/demon_overseer.png',
        hp: 5,
        atk: 2,
        armor: 2,
        unitType: 'melee',
        jobType: JobType.DEMON,
        traits: [Trait.AMPLIFY],
        traitValues: { [Trait.AMPLIFY]: 1 }
    },
    {
        id: 'minion_007',
        name: '火焰元素',
        description: '受到攻击时反击造成2点伤害。',
        type: 'unit',
        cost: 4,
        image: 'elemental',
        rarity: 'rare',
        imagePath: 'assets/images/minions/fire_elemental.png',
        hp: 4,
        atk: 3,
        armor: 0,
        unitType: 'ranged',
        jobType: JobType.ELEMENTAL,
        traits: [Trait.COUNTER],
        traitValues: { [Trait.COUNTER]: 2 }
    },
    {
        id: 'minion_008',
        name: '灾厄领主',
        description: '高级恶魔单位，具有穿刺特性，伤害无视护甲。',
        type: 'unit',
        cost: 5,
        image: 'doomlord',
        rarity: 'epic',
        imagePath: 'assets/images/minions/doom_lord.png',
        hp: 6,
        atk: 4,
        armor: 3,
        unitType: 'melee',
        jobType: JobType.DEMON,
        traits: [Trait.PIERCE],
        traitValues: {}
    },
    {
        id: 'minion_009',
        name: '深渊治疗师',
        description: '每回合开始时，治疗相邻友方单位2点生命值。',
        type: 'unit',
        cost: 3,
        image: 'healer',
        rarity: 'rare',
        imagePath: 'assets/images/minions/abyss_healer.png',
        hp: 3,
        atk: 1,
        armor: 1,
        unitType: 'ranged',
        jobType: JobType.DEMON,
        traits: [Trait.HEALING],
        traitValues: { [Trait.HEALING]: 2 }
    },
    {
        id: 'minion_010',
        name: '恶魔王子',
        description: '每回合自动回复1点生命值，首次受到攻击时免疫伤害。',
        type: 'unit',
        cost: 6,
        image: 'prince',
        rarity: 'legendary',
        imagePath: 'assets/images/minions/demon_prince.png',
        hp: 8,
        atk: 5,
        armor: 3,
        unitType: 'melee',
        jobType: JobType.DEMON,
        traits: [Trait.REGENERATION, Trait.SHIELD],
        traitValues: { [Trait.REGENERATION]: 1 }
    }
]; 